name: Publish to main 
on:
  schedule:
    - cron: '*/30 * * * *'    # At every 30th minute
  workflow_dispatch:
    inputs:
      ref:
        description: "The Operator branch/tag to checkout when creating the image."
        required: true
        default: "release_operator_image"
      prev_version:
        description: "The Operator version to replace"

env:
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} 
  release-version: ${{ github.event.inputs.ref }}
  replace_version: ${{ github.event.inputs.prev_version }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"

      - name: Checkout
        uses: actions/checkout@v2
        with: 
           path: operator
    
          