name: Post Release - Update CSV
on:
  schedule:
    - cron: '* * * * *'    # At every  minute
    
env:
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}   
  release-version: '${{ github.event.inputs.tag }}'
  replace_version: '${{ github.event.inputs.old_version }}'
  
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Remove scheduled job after 1 attempts
        uses: cardinalby/unschedule-job-action@v1
        if: github.run_number > 2
        with:
          ghToken: ${{ secrets.PAT_TOKEN }} 
          deleteRefTag: false

      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if the image exists
        run:  |
          docker manifest inspect quay.io/pminz/operator-images:${{ env.release-version}} > /dev/null
         
      - name: Update CSV file to Next version and Push to main 
        if: success()
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'config/manifests/bases/*-operator.clusterserviceversion.yaml'
          branch: main
          message: 'Next Version ${{ env.release-version }}'
          commitUserName: 'pminz'
          commitUserEmail: 'pminz@redhat.com'
          token: ${{ secrets.MY_TOKEN }}   
          changes: |
            {
              "spec.replaces": "gingersnap.v${{ env.replace_version }}"
            }
            
      - name: Remove scheduled job after 10 attempts
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: ${{ secrets.MY_TOKEN }} 
          deleteRefTag: false