name: Publish Images

on:
  push:
    branches:
      - 'cron_job'


jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"

      - name: Checkout
        uses: actions/checkout@v3

  publish:
      needs: tag
      uses: ./.github/workflows/cron-tab.yaml
      secrets: inherit
      with:
        ref: main
        repository: pminz/operator