name: Post Release - Update CSV
'on':
  schedule:
    - cron: '* * * * *'
env:
  GITHUB_TOKEN: '${{ secrets.MY_TOKEN }}'
  release-version: '${{ github.event.inputs.tag }}'
  replace_version: '${{ github.event.inputs.old_version }}'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redaht.com"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: operator
      - name: Check if the image exists
        run: >
          docker manifest inspect quay.io/operatorhubio/gingersnap:v${{
          env.release-version}} > /dev/null
      - name: Update CSV file to Next version and Push to main
        if: '${{ success() && inputs.prev_version }}'
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: config/manifests/bases/*-operator.clusterserviceversion.yaml
          branch: main
          message: 'Next Version ${{ env.release-version }}'
          commitUserName: pminz
          commitUserEmail: pminz@redhat.com
          token: '${{ secrets.MY_TOKEN }}'
          changes: |
            {
              "replaces": "gingersnap-operator.v${{ env.replace_version }}"
            }
      - name: Remove scheduled job after 10 attempts
        uses: cardinalby/unschedule-job-action@v1
        if: github.run_number > 2
        with:
          ghToken: '${{ secrets.MY_TOKEN }}'
          deleteRefTag: false
    env:
      DELAYED_JOB_CHECKOUT_REF: 9312d524b02951c1b4d354a757ce9de9b248b201
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: .github/workflows/publish-main.yaml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
