name: Publish to main
'on':
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      ref:
        description: The Operator branch/tag to checkout when creating the image.
        required: true
        default: release_operator_image
      prev_version:
        description: The Operator version to replace
env:
  GITHUB_TOKEN: '${{ secrets.PAT_TOKEN }}'
  release-version: '${{ github.event.inputs.ref }}'
  replace_version: '${{ github.event.inputs.prev_version }}'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: operator
      - name: Check if the image exists
        run: >
          docker manifest inspect quay.io/operatorhubio/gingersnap:v${{
          env.release-version}} > /dev/null

      - name: Debug
        run: |
             ls -lrt
             pwd
             tree
             
      - name: Update CSV file to Next version and Push to main
        if: success() 
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: config/manifests/bases/*-operator.clusterserviceversion.yaml
          branch: main
          message: 'Next Version ${{ env.release-version }}'
          commitUserName: infinispan-qe-bot
          commitUserEmail: q*@infinispan.org
          token: '${{ secrets.PAT_TOKEN }}'
          changes: |
            {
              "replaces": "gingersnap-operator.v${{ env.replace_version }}"
            }
    env:
      DELAYED_JOB_CHECKOUT_REF: 58ed60b8a831219a3b59e8010ec5a8e1c9ba1a4f
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: .github/workflows/publish-main.yaml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
