name: Gingersnap Operator - Build and publish

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
      repository:
        type: string
        default: ${{ github.repository }}
      tag:
        type: string
        default: latest
      
env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}   
  release-version: ${{ github.event.inputs.tag }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "infinispan-qe-bot"
          git config --global user.email "q*@infinispan.org"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          token: ${{ env.GITHUB_TOKEN }}
          path: operator

      - name: Tag the release
        run: |
          cd operator
          ls -lrt
          pwd
          tree

      - name: Checkout community-operators repo
        uses: actions/checkout@v2
        with:
          repository: k8s-operatorhub/community-operators
          path: community-operators
          ref: main

      - name: Copy contents of bundle/ 
        run: |
          cd community-operators
          ls -lrt
          pwd
          tree

      - name: Checkout community-operators-prod repo
        uses: actions/checkout@v3
        with:
          repository: redhat-openshift-ecosystem/community-operators-prod
          path: community-operators-prod
          ref: main

      - name: Copy contents of bundle/ and issue PRs
        run: |
          cd community-operators-prod
          ls -lrt
          pwd
          tree

