name: Gingersnap Operator - Build and publish

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: main
      repository:
        type: string
        default: gingersnap-project/operator
      tag:
        type: string
        default: latest
      prev_version:
        type: string
      
env:
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}   
  release-version: ${{ github.event.inputs.tag }}
  replace_version: ${{ github.event.inputs.prev_version }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          token: ${{ env.GITHUB_TOKEN }}
          path: operator

      - name: Trigger Publish to main job
        uses: cardinalby/schedule-job-action@v1
        with:
         ghToken: ${{ secrets.MY_TOKEN }}
         targetBranch: 'main'
         templateYmlFile: './operator/.github-scheduled-workflows/publish-main.yaml'
         targetYmlFileName: publish-main.yaml
         copyEnvVariables: true

