name: Gingersnap Operator - Build and publish

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
      repository:
        type: string
        default: ${{ github.repository }}
      tag:
        type: string
        default: latest
      
env:
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}   
  release-version: ${{ github.event.inputs.tag }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          token: ${{ env.GITHUB_TOKEN }}

      - name: Tag the release
        run: |
          ls -lrt
          pwd
          tree

      - name: Checkout community-operators repo
        uses: actions/checkout@v2
        with:
          repository: pminz/community-operators
          ref: main

      - name: Copy contents of bundle/ 
        run: |
          ls -lrt
          pwd
          tree

      - name: Checkout community-operators-prod repo
        uses: actions/checkout@v3
        with:
          repository: pminz/community-operators-prod
          ref: main

      - name: Copy contents of bundle/ and issue PRs
        run: |
          ls -lrt
          pwd
          tree

